default_provider = "pass"

[providers.protonpass]
type = "proton-pass"
vault = "System"

[secrets]
CLOUDFLARE_API_TOKEN= { provider = "protonpass", value = "cloudflare/api_token" }
POSTGRES_PASSWORD= { provider = "protonpass", value = "postgres/password" }
KESTRA_DB_PASSWORD= { provider = "protonpass", value = "postgres/kestra_password" }
READECK_DB_PASSWORD= { provider = "protonpass", value = "postgres/readeck_password" }
LIBRECHAT_DB_PASSWORD= { provider = "protonpass", value = "postgres/librechat_password" }
MONGO_INITDB_ROOT_PASSWORD= { provider = "protonpass", value = "mongo/password" }
LIBRECHAT_MONGODB_PASSWORD= { provider = "protonpass", value = "mongo/librechat_password" }
MEILI_MASTER_KEY= { provider = "protonpass", value = "meili/master_key" }
FIZZY_API_BASE_URL= { provider = "protonpass", value = "fizzy/API_BASE_URL" }
FIZZY_API_TOKEN= { provider = "protonpass", value = "fizzy/API_TOKEN" }

FIZZY_MAILER_FROM_ADDRESS= { provider = "protonpass", value = "fizzy/MAILER_FROM_ADDRESS" }
FIZZY_SMTP_ADDRESS= { provider = "protonpass", value = "fizzy/SMTP_ADDRESS" }
FIZZY_SMTP_PORT= { provider = "protonpass", value = "fizzy/SMTP_PORT" }
FIZZY_SMTP_USERNAME= { provider = "protonpass", value = "fizzy/SMTP_USERNAME" }
FIZZY_SECRET_BASE_KEY= { provider = "protonpass", value = "fizzy/SECRET_BASE_KEY" }
FIZZY_SMTP_PASSWORD= { provider = "protonpass", value = "fizzy/SMTP_PASSWORD" }
TF_VAR_state_bucket= { provider = "protonpass", value = "terraform/state_bucket" }
TF_VAR_domain= { provider = "protonpass", value = "terraform/domain" }
TF_VAR_cloudflare_zone_id= { provider = "protonpass", value = "terraform/cloudflare_zone_id" }
TF_VAR_cloudflare_api_token= { provider = "protonpass", value = "terraform/cloudflare_api_token" }
TF_VAR_cloudflare_r2_token= { provider = "protonpass", value = "terraform/cloudflare_r2_token" }
TF_VAR_cloudflare_r2_account_id= { provider = "protonpass", value = "terraform/cloudflare_r2_account_id" }
