FROM nvidia/cuda:12.9.0-runtime-ubuntu22.04
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install system dependencies
RUN apt-get update && apt-get install -y \
  git python3 wget libgl1 libglib2.0-0 \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Clone ComfyUI
RUN git clone https://github.com/comfyanonymous/ComfyUI.git
WORKDIR /app/ComfyUI

RUN uv venv .venv

# Install PyTorch wit GPU support
RUN uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
RUN uv pip install -r requirements.txt

# Expose UI port
EXPOSE 8188

# Run ComfyUI
CMD ["uv", "run", "main.py", "--listen", "0.0.0.0"]
